"""empty message

Revision ID: 3e7f3df84c9e
Revises: None
Create Date: 2013-12-10 16:23:31.482098

"""

# revision identifiers, used by Alembic.
revision = '3e7f3df84c9e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('site_url', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jar_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['jar_id'], ['jars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jar_id','name', name='uix_1')
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id','version', name='uix_1')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('build', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id','build', name='uix_1')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('builds')
    op.drop_table('versions')
    op.drop_table('channels')
    op.drop_table('jars')
    ### end Alembic commands ###
