"""Revises to allow for description of jars.

Revision ID: 4aab0be23fc9
Revises: 3df41fbd302d
Create Date: 2014-03-10 14:59:13.026071

"""

# revision identifiers, used by Alembic.
revision = '4aab0be23fc9'
down_revision = '3df41fbd302d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jars', sa.Column('description', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jars', 'description')
    ### end Alembic commands ###
