from json_loader import *
from jenkins_loader import *
from craftbukkit_loader import *
from mojang_loader import *
from creeperrepo_loader import *
from pixelmon_loader import *
from tekkit_loader import *
from direct_loader import *
from cauldron_loader import *